ALTER TABLE "employee_projects" ALTER COLUMN "employee_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_projects" ALTER COLUMN "project_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_projects" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_trainings" ALTER COLUMN "employee_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_trainings" ALTER COLUMN "training_date" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_trainings" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "warnings" ALTER COLUMN "company_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "warnings" ALTER COLUMN "warning_grade_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "warnings" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "warnings" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_warnings" ALTER COLUMN "employee_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_warnings" ALTER COLUMN "warning_start_date" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_warnings" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "working_zones" ALTER COLUMN "company_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "working_zones" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "working_zones" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "cost_centers" ALTER COLUMN "sap_code" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "cost_centers" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "cost_centers" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "training_schedules" ALTER COLUMN "company_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "training_schedules" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "religion" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "religion" ALTER COLUMN "description" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "religion" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_leave_advisors" ALTER COLUMN "employee_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_leave_advisors" ALTER COLUMN "order" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_leave_advisors" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_addresses" ALTER COLUMN "employee_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_addresses" ALTER COLUMN "address" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_addresses" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_contracts" ALTER COLUMN "employee_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_contracts" ALTER COLUMN "start_date" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_contracts" ALTER COLUMN "end_date" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_contracts" ALTER COLUMN "termination_date" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_contracts" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "allowances" ALTER COLUMN "company_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "allowances" ALTER COLUMN "currency_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "allowances" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "allowances" ALTER COLUMN "nominal" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "allowances" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "trainings" ALTER COLUMN "company_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "trainings" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "trainings" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "warning_grades" ALTER COLUMN "company_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "warning_grades" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "warning_grades" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "training_types" ALTER COLUMN "company_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "training_types" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "training_types" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_mcus" ALTER COLUMN "employee_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_mcus" ALTER COLUMN "mcu_date" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_mcus" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "grades" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "grades" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_work_zones" ALTER COLUMN "employee_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_work_zones" ALTER COLUMN "working_zone_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_work_zones" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_contract_advisors" ALTER COLUMN "employee_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_contract_advisors" ALTER COLUMN "order" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee_contract_advisors" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "company_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "department_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "position_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "finger_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "first_name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "email" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "remark" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "sap_code" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "remark" SET NOT NULL;