export const EmployeeTypes = {
  // Employee + employee sub-tables
  EmployeeRepositoryInterface: Symbol.for("EmployeeRepositoryInterface"),
  EmployeeServiceInterface: Symbol.for("EmployeeServiceInterface"),
  EmployeeAddressRepositoryInterface: Symbol.for("EmployeeAddressRepositoryInterface"),
  EmployeeAddressServiceInterface: Symbol.for("EmployeeAddressServiceInterface"),
  EmployeeContractRepositoryInterface: Symbol.for("EmployeeContractRepositoryInterface"),
  EmployeeContractServiceInterface: Symbol.for("EmployeeContractServiceInterface"),
  EmployeeContractAdvisorRepositoryInterface: Symbol.for("EmployeeContractAdvisorRepositoryInterface"),
  EmployeeContractAdvisorServiceInterface: Symbol.for("EmployeeContractAdvisorServiceInterface"),
  EmployeeLeaveAdvisorRepositoryInterface: Symbol.for("EmployeeLeaveAdvisorRepositoryInterface"),
  EmployeeLeaveAdvisorServiceInterface: Symbol.for("EmployeeLeaveAdvisorServiceInterface"),
  EmployeeMcuRepositoryInterface: Symbol.for("EmployeeMcuRepositoryInterface"),
  EmployeeMcuServiceInterface: Symbol.for("EmployeeMcuServiceInterface"),
  EmployeeProjectRepositoryInterface: Symbol.for("EmployeeProjectRepositoryInterface"),
  EmployeeProjectServiceInterface: Symbol.for("EmployeeProjectServiceInterface"),
  EmployeeTrainingRepositoryInterface: Symbol.for("EmployeeTrainingRepositoryInterface"),
  EmployeeTrainingServiceInterface: Symbol.for("EmployeeTrainingServiceInterface"),
  EmployeeWarningRepositoryInterface: Symbol.for("EmployeeWarningRepositoryInterface"),
  EmployeeWarningServiceInterface: Symbol.for("EmployeeWarningServiceInterface"),
  EmployeeWorkZoneRepositoryInterface: Symbol.for("EmployeeWorkZoneRepositoryInterface"),
  EmployeeWorkZoneServiceInterface: Symbol.for("EmployeeWorkZoneServiceInterface"),
} as const;
