export const MasterTypes = {
  // Master tables
  CountryRepositoryInterface: Symbol.for("CountryRepositoryInterface"),
  CountryServiceInterface: Symbol.for("CountryServiceInterface"),
  ReligionRepositoryInterface: Symbol.for("ReligionRepositoryInterface"),
  ReligionServiceInterface: Symbol.for("ReligionServiceInterface"),
  GradeRepositoryInterface: Symbol.for("GradeRepositoryInterface"),
  GradeServiceInterface: Symbol.for("GradeServiceInterface"),
  CostCenterRepositoryInterface: Symbol.for("CostCenterRepositoryInterface"),
  CostCenterServiceInterface: Symbol.for("CostCenterServiceInterface"),
  ProjectRepositoryInterface: Symbol.for("ProjectRepositoryInterface"),
  ProjectServiceInterface: Symbol.for("ProjectServiceInterface"),
  CompanyRepositoryInterface: Symbol.for("CompanyRepositoryInterface"),
  CompanyServiceInterface: Symbol.for("CompanyServiceInterface"),
  DepartmentRepositoryInterface: Symbol.for("DepartmentRepositoryInterface"),
  DepartmentServiceInterface: Symbol.for("DepartmentServiceInterface"),
  PositionRepositoryInterface: Symbol.for("PositionRepositoryInterface"),
  PositionServiceInterface: Symbol.for("PositionServiceInterface"),
  AllowanceRepositoryInterface: Symbol.for("AllowanceRepositoryInterface"),
  AllowanceServiceInterface: Symbol.for("AllowanceServiceInterface"),
  WarningGradeRepositoryInterface: Symbol.for("WarningGradeRepositoryInterface"),
  WarningGradeServiceInterface: Symbol.for("WarningGradeServiceInterface"),
  WarningRepositoryInterface: Symbol.for("WarningRepositoryInterface"),
  WarningServiceInterface: Symbol.for("WarningServiceInterface"),
  TrainingTypeRepositoryInterface: Symbol.for("TrainingTypeRepositoryInterface"),
  TrainingTypeServiceInterface: Symbol.for("TrainingTypeServiceInterface"),
  TrainingRepositoryInterface: Symbol.for("TrainingRepositoryInterface"),
  TrainingServiceInterface: Symbol.for("TrainingServiceInterface"),
  TrainingScheduleRepositoryInterface: Symbol.for("TrainingScheduleRepositoryInterface"),
  TrainingScheduleServiceInterface: Symbol.for("TrainingScheduleServiceInterface"),
  WorkingZoneRepositoryInterface: Symbol.for("WorkingZoneRepositoryInterface"),
  WorkingZoneServiceInterface: Symbol.for("WorkingZoneServiceInterface"),
} as const;
