// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface AllowanceResponseDto {
  id: string | null;
  companyId: string;
  currencyId: string;
  name: string;
  nominal: number;
  remark: string | null;
}

import { z } from "zod";

export const CreateAllowanceSchema = z.object({
  companyId: z.string().min(1, "CompanyId is required"),
  currencyId: z.string().min(1, "CurrencyId is required"),
  name: z.string().min(1, "Name is required"),
  nominal: z.coerce.number(),
  remark: z.string().optional(),
});
export type CreateAllowanceDto = z.infer<typeof CreateAllowanceSchema>;

export const UpdateAllowanceSchema = z.object({
  companyId: z.string().min(1).optional(),
  currencyId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  nominal: z.coerce.number().optional(),
  remark: z.string().optional(),
});
export type UpdateAllowanceDto = z.infer<typeof UpdateAllowanceSchema>;