// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface ALlowanceResponseDto {
  id: string | null;
  companyId: string;
  currencyId: string;
  name: string;
  nominal: number;
  remark: string | null;
}

import { z } from "zod";

export const CreateALlowanceSchema = z.object({
  companyId: z.string().min(1, "COmpanyId is required"),
  currencyId: z.string().min(1, "CUrrencyId is required"),
  name: z.string().min(1, "NAme is required"),
  nominal: z.coerce.number(),
  remark: z.string().optional(),
});
export type CreateALlowanceDto = z.infer<typeof CreateALlowanceSchema>;

export const UpdateALlowanceSchema = z.object({
  companyId: z.string().min(1).optional(),
  currencyId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  nominal: z.coerce.number().optional(),
  remark: z.string().optional(),
});
export type UpdateALlowanceDto = z.infer<typeof UpdateALlowanceSchema>;