// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface CostCenterResponseDto {
  id: string | null;
  sapCode: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateCostCenterSchema = z.object({
  sapCode: z.string().min(1, "SapCode is required"),
  name: z.string().min(1, "Name is required"),
  remark: z.string().optional(),
});
export type CreateCostCenterDto = z.infer<typeof CreateCostCenterSchema>;

export const UpdateCostCenterSchema = z.object({
  sapCode: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateCostCenterDto = z.infer<typeof UpdateCostCenterSchema>;