// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface CountryResponseDto {
  id: string;
  code: string | null;
  currency: string | null;
  flag: string | null;
  stsActive: boolean | null;
  createdAt: Date;
  createdBy: string | null;
  updatedAt: Date | null;
  updatedBy: string | null;
  deletedAt: Date | null;
}

import { z } from "zod";

export const CreateCountrySchema = z.object({
  code: z.string().optional(),
  currency: z.string().optional(),
  flag: z.string().optional(),
});
export type CreateCountryDto = z.infer<typeof CreateCountrySchema>;

export const UpdateCountrySchema = z.object({
  code: z.string().optional(),
  currency: z.string().optional(),
  flag: z.string().optional(),
});
export type UpdateCountryDto = z.infer<typeof UpdateCountrySchema>;
