// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface DEpartmentResponseDto {
  id: string | null;
  companyId: string | null;
  name: string | null;
}

import { z } from "zod";

export const CreateDEpartmentSchema = z.object({
  companyId: z.string().optional(),
  name: z.string().optional(),
});
export type CreateDEpartmentDto = z.infer<typeof CreateDEpartmentSchema>;

export const UpdateDEpartmentSchema = z.object({
  companyId: z.string().optional(),
  name: z.string().optional(),
});
export type UpdateDEpartmentDto = z.infer<typeof UpdateDEpartmentSchema>;