// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface DepartmentResponseDto {
  id: string | null;
  companyId: string | null;
  name: string | null;
}

import { z } from "zod";

export const CreateDepartmentSchema = z.object({
  companyId: z.string().optional(),
  name: z.string().optional(),
});
export type CreateDepartmentDto = z.infer<typeof CreateDepartmentSchema>;

export const UpdateDepartmentSchema = z.object({
  companyId: z.string().optional(),
  name: z.string().optional(),
});
export type UpdateDepartmentDto = z.infer<typeof UpdateDepartmentSchema>;