// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeContractAdvisorResponseDto {
  id: string | null;
  employeeId: string;
  order: number;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeContractAdvisorSchema = z.object({
  employeeId: z.string().min(1, "EmployeeId is required"),
  order: z.number().int(),
  remark: z.string().optional(),
});
export type CreateEmployeeContractAdvisorDto = z.infer<typeof CreateEmployeeContractAdvisorSchema>;

export const UpdateEmployeeContractAdvisorSchema = z.object({
  employeeId: z.string().min(1).optional(),
  order: z.number().int().optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeContractAdvisorDto = z.infer<typeof UpdateEmployeeContractAdvisorSchema>;