// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeTrainingResponseDto {
  id: string | null;
  employeeId: string;
  trainingDate: Date;
  trainingStatus: "PASS" | "FAILED" | "REGISTERED" | "NOTATTEND" | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeTrainingSchema = z.object({
  employeeId: z.string().min(1, "EMployeeId is required"),
  trainingDate: z.coerce.date(),
  trainingStatus: z.enum(["PASS", "FAILED", "REGISTERED", "NOTATTEND"]).optional(),
  remark: z.string().optional(),
});
export type CreateEMployeeTrainingDto = z.infer<typeof CreateEMployeeTrainingSchema>;

export const UpdateEMployeeTrainingSchema = z.object({
  employeeId: z.string().min(1).optional(),
  trainingDate: z.coerce.date().optional(),
  trainingStatus: z.enum(["PASS", "FAILED", "REGISTERED", "NOTATTEND"]).optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeTrainingDto = z.infer<typeof UpdateEMployeeTrainingSchema>;