// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeTrainingResponseDto {
  id: string | null;
  employeeId: string;
  trainingDate: Date;
  trainingStatus: "PASS" | "FAILED" | "REGISTERED" | "NOTATTEND" | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeTrainingSchema = z.object({
  employeeId: z.string().min(1, "EmployeeId is required"),
  trainingDate: z.coerce.date(),
  trainingStatus: z.enum(["PASS", "FAILED", "REGISTERED", "NOTATTEND"]).optional(),
  remark: z.string().optional(),
});
export type CreateEmployeeTrainingDto = z.infer<typeof CreateEmployeeTrainingSchema>;

export const UpdateEmployeeTrainingSchema = z.object({
  employeeId: z.string().min(1).optional(),
  trainingDate: z.coerce.date().optional(),
  trainingStatus: z.enum(["PASS", "FAILED", "REGISTERED", "NOTATTEND"]).optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeTrainingDto = z.infer<typeof UpdateEmployeeTrainingSchema>;