// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeLeaveAdvisorResponseDto {
  id: string | null;
  employeeId: string;
  order: number;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeLeaveAdvisorSchema = z.object({
  employeeId: z.string().min(1, "EmployeeId is required"),
  order: z.number().int(),
  remark: z.string().optional(),
});
export type CreateEmployeeLeaveAdvisorDto = z.infer<typeof CreateEmployeeLeaveAdvisorSchema>;

export const UpdateEmployeeLeaveAdvisorSchema = z.object({
  employeeId: z.string().min(1).optional(),
  order: z.number().int().optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeLeaveAdvisorDto = z.infer<typeof UpdateEmployeeLeaveAdvisorSchema>;