// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeMcuResponseDto {
  id: string | null;
  employeeId: string;
  mcuDate: Date;
  mcuEndDate: Date | null;
  mcuStatus: "PASS" | "FAILED" | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeMcuSchema = z.object({
  employeeId: z.string().uuid("EMployeeId is required must be a valid UUID"),
  mcuDate: z.coerce.date(),
  mcuEndDate: z.coerce.date().optional(),
  mcuStatus: z.enum(["PASS", "FAILED"]).optional(),
  remark: z.string().optional(),
});
export type CreateEMployeeMcuDto = z.infer<typeof CreateEMployeeMcuSchema>;

export const UpdateEMployeeMcuSchema = z.object({
  employeeId: z.string().uuid().optional(),
  mcuDate: z.coerce.date().optional(),
  mcuEndDate: z.coerce.date().optional(),
  mcuStatus: z.enum(["PASS", "FAILED"]).optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeMcuDto = z.infer<typeof UpdateEMployeeMcuSchema>;