// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeWorkZoneResponseDto {
  id: string | null;
  employeeId: string;
  workingZoneId: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeWorkZoneSchema = z.object({
  employeeId: z.string().min(1, "EMployeeId is required"),
  workingZoneId: z.string().min(1, "WOrkingZoneId is required"),
  remark: z.string().optional(),
});
export type CreateEMployeeWorkZoneDto = z.infer<typeof CreateEMployeeWorkZoneSchema>;

export const UpdateEMployeeWorkZoneSchema = z.object({
  employeeId: z.string().min(1).optional(),
  workingZoneId: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeWorkZoneDto = z.infer<typeof UpdateEMployeeWorkZoneSchema>;