// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeContractResponseDto {
  id: string | null;
  employeeId: string;
  startDate: Date;
  endDate: Date;
  terminationDate: Date;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeContractSchema = z.object({
  employeeId: z.string().min(1, "EmployeeId is required"),
  startDate: z.coerce.date(),
  endDate: z.coerce.date(),
  terminationDate: z.coerce.date(),
  remark: z.string().optional(),
});
export type CreateEmployeeContractDto = z.infer<typeof CreateEmployeeContractSchema>;

export const UpdateEmployeeContractSchema = z.object({
  employeeId: z.string().min(1).optional(),
  startDate: z.coerce.date().optional(),
  endDate: z.coerce.date().optional(),
  terminationDate: z.coerce.date().optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeContractDto = z.infer<typeof UpdateEmployeeContractSchema>;