// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeAddressResponseDto {
  id: string | null;
  employeeId: string;
  address: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeAddressSchema = z.object({
  employeeId: z.string().min(1, "EMployeeId is required"),
  address: z.string().min(1, "ADdress is required"),
  remark: z.string().optional(),
});
export type CreateEMployeeAddressDto = z.infer<typeof CreateEMployeeAddressSchema>;

export const UpdateEMployeeAddressSchema = z.object({
  employeeId: z.string().min(1).optional(),
  address: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeAddressDto = z.infer<typeof UpdateEMployeeAddressSchema>;