// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeContractResponseDto {
  id: string | null;
  employeeId: string;
  startDate: Date;
  endDate: Date;
  terminationDate: Date;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeContractSchema = z.object({
  employeeId: z.string().uuid("EMployeeId is required must be a valid UUID"),
  startDate: z.coerce.date(),
  endDate: z.coerce.date(),
  terminationDate: z.coerce.date(),
  remark: z.string().optional(),
});
export type CreateEMployeeContractDto = z.infer<typeof CreateEMployeeContractSchema>;

export const UpdateEMployeeContractSchema = z.object({
  employeeId: z.string().uuid().optional(),
  startDate: z.coerce.date().optional(),
  endDate: z.coerce.date().optional(),
  terminationDate: z.coerce.date().optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeContractDto = z.infer<typeof UpdateEMployeeContractSchema>;