// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeResponseDto {
  id: string | null;
  companyId: string;
  departmentId: string;
  positionId: string;
  supervisorId: string | null;
  fingerId: string;
  firstName: string;
  middleName: string | null;
  lastName: string | null;
  email: string;
  phone: string | null;
  mobile: string | null;
  birthDate: Date | null;
  birthPlace: string | null;
  gender: "M" | "W" | null;
  maritalStatus: "SINGLE" | "MARRIED" | "DIVORCED" | null;
  employeeType: "STAFF" | "WORKER" | null;
  employeeStatus: "PERMANENT" | "CONTRACT" | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeSchema = z.object({
  companyId: z.string().uuid("COmpanyId is required must be a valid UUID"),
  departmentId: z.string().uuid("DEpartmentId is required must be a valid UUID"),
  positionId: z.string().uuid("POsitionId is required must be a valid UUID"),
  supervisorId: z.string().optional(),
  fingerId: z.string().min(1, "FingerId is required"),
  firstName: z.string().min(1, "FIrstName is required"),
  middleName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().min(1, "EMail is required"),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  birthDate: z.coerce.date().optional(),
  birthPlace: z.string().optional(),
  gender: z.enum(["M", "W"]).optional(),
  maritalStatus: z.enum(["SINGLE", "MARRIED", "DIVORCED"]).optional(),
  employeeType: z.enum(["STAFF", "WORKER"]).optional(),
  employeeStatus: z.enum(["PERMANENT", "CONTRACT"]).optional(),
  remark: z.string().optional(),
});
export type CreateEMployeeDto = z.infer<typeof CreateEMployeeSchema>;

export const UpdateEMployeeSchema = z.object({
  companyId: z.string().uuid().optional(),
  departmentId: z.string().uuid().optional(),
  positionId: z.string().uuid().optional(),
  supervisorId: z.string().optional(),
  fingerId: z.string().min(1).optional(),
  firstName: z.string().min(1).optional(),
  middleName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().min(1).optional(),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  birthDate: z.coerce.date().optional(),
  birthPlace: z.string().optional(),
  gender: z.enum(["M", "W"]).optional(),
  maritalStatus: z.enum(["SINGLE", "MARRIED", "DIVORCED"]).optional(),
  employeeType: z.enum(["STAFF", "WORKER"]).optional(),
  employeeStatus: z.enum(["PERMANENT", "CONTRACT"]).optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeDto = z.infer<typeof UpdateEMployeeSchema>;