// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeMcuResponseDto {
  id: string | null;
  employeeId: string;
  mcuDate: Date;
  mcuEndDate: Date | null;
  mcuStatus: "PASS" | "FAILED" | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeMcuSchema = z.object({
  employeeId: z.string().min(1, "EmployeeId is required"),
  mcuDate: z.coerce.date(),
  mcuEndDate: z.coerce.date().optional(),
  mcuStatus: z.enum(["PASS", "FAILED"]).optional(),
  remark: z.string().optional(),
});
export type CreateEmployeeMcuDto = z.infer<typeof CreateEmployeeMcuSchema>;

export const UpdateEmployeeMcuSchema = z.object({
  employeeId: z.string().min(1).optional(),
  mcuDate: z.coerce.date().optional(),
  mcuEndDate: z.coerce.date().optional(),
  mcuStatus: z.enum(["PASS", "FAILED"]).optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeMcuDto = z.infer<typeof UpdateEmployeeMcuSchema>;