// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeResponseDto {
  id: string | null;
  companyId: string;
  departmentId: string;
  positionId: string;
  supervisorId: string | null;
  fingerId: string;
  firstName: string;
  middleName: string | null;
  lastName: string | null;
  email: string;
  phone: string | null;
  mobile: string | null;
  birthDate: Date | null;
  birthPlace: string | null;
  gender: "M" | "W" | null;
  maritalStatus: "SINGLE" | "MARRIED" | "DIVORCED" | null;
  employeeType: "STAFF" | "WORKER" | null;
  employeeStatus: "PERMANENT" | "CONTRACT" | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeSchema = z.object({
  companyId: z.string().min(1, "CompanyId is required"),
  departmentId: z.string().min(1, "DepartmentId is required"),
  positionId: z.string().min(1, "PositionId is required"),
  supervisorId: z.string().optional(),
  fingerId: z.string().min(1, "FingerId is required"),
  firstName: z.string().min(1, "FirstName is required"),
  middleName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().min(1, "Email is required"),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  birthDate: z.coerce.date().optional(),
  birthPlace: z.string().optional(),
  gender: z.enum(["M", "W"]).optional(),
  maritalStatus: z.enum(["SINGLE", "MARRIED", "DIVORCED"]).optional(),
  employeeType: z.enum(["STAFF", "WORKER"]).optional(),
  employeeStatus: z.enum(["PERMANENT", "CONTRACT"]).optional(),
  remark: z.string().optional(),
});
export type CreateEmployeeDto = z.infer<typeof CreateEmployeeSchema>;

export const UpdateEmployeeSchema = z.object({
  companyId: z.string().min(1).optional(),
  departmentId: z.string().min(1).optional(),
  positionId: z.string().min(1).optional(),
  supervisorId: z.string().optional(),
  fingerId: z.string().min(1).optional(),
  firstName: z.string().min(1).optional(),
  middleName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().min(1).optional(),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  birthDate: z.coerce.date().optional(),
  birthPlace: z.string().optional(),
  gender: z.enum(["M", "W"]).optional(),
  maritalStatus: z.enum(["SINGLE", "MARRIED", "DIVORCED"]).optional(),
  employeeType: z.enum(["STAFF", "WORKER"]).optional(),
  employeeStatus: z.enum(["PERMANENT", "CONTRACT"]).optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeDto = z.infer<typeof UpdateEmployeeSchema>;