// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeProjectResponseDto {
  employeeId: string;
  projectId: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeProjectSchema = z.object({
  employeeId: z.string().min(1, "EmployeeId is required"),
  projectId: z.string().min(1, "ProjectId is required"),
  remark: z.string().optional(),
});
export type CreateEmployeeProjectDto = z.infer<typeof CreateEmployeeProjectSchema>;

export const UpdateEmployeeProjectSchema = z.object({
  employeeId: z.string().min(1).optional(),
  projectId: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeProjectDto = z.infer<typeof UpdateEmployeeProjectSchema>;