// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeProjectResponseDto {
  employeeId: string;
  projectId: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeProjectSchema = z.object({
  employeeId: z.string().min(1, "EMployeeId is required"),
  projectId: z.string().min(1, "PRojectId is required"),
  remark: z.string().optional(),
});
export type CreateEMployeeProjectDto = z.infer<typeof CreateEMployeeProjectSchema>;

export const UpdateEMployeeProjectSchema = z.object({
  employeeId: z.string().min(1).optional(),
  projectId: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeProjectDto = z.infer<typeof UpdateEMployeeProjectSchema>;