// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeAddressResponseDto {
  id: string | null;
  employeeId: string;
  address: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeAddressSchema = z.object({
  employeeId: z.string().min(1, "EmployeeId is required"),
  address: z.string().min(1, "Address is required"),
  remark: z.string().optional(),
});
export type CreateEmployeeAddressDto = z.infer<typeof CreateEmployeeAddressSchema>;

export const UpdateEmployeeAddressSchema = z.object({
  employeeId: z.string().min(1).optional(),
  address: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeAddressDto = z.infer<typeof UpdateEmployeeAddressSchema>;