// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeWorkZoneResponseDto {
  id: string | null;
  employeeId: string;
  workingZoneId: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeWorkZoneSchema = z.object({
  employeeId: z.string().min(1, "EmployeeId is required"),
  workingZoneId: z.string().min(1, "WorkingZoneId is required"),
  remark: z.string().optional(),
});
export type CreateEmployeeWorkZoneDto = z.infer<typeof CreateEmployeeWorkZoneSchema>;

export const UpdateEmployeeWorkZoneSchema = z.object({
  employeeId: z.string().min(1).optional(),
  workingZoneId: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeWorkZoneDto = z.infer<typeof UpdateEmployeeWorkZoneSchema>;