// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeWarningResponseDto {
  id: string | null;
  employeeId: string;
  warningStartDate: Date;
  warningEndDate: Date | null;
  warningStatus: "PERMANENT" | "TEMPORARY" | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeWarningSchema = z.object({
  employeeId: z.string().uuid("EMployeeId is required must be a valid UUID"),
  warningStartDate: z.coerce.date(),
  warningEndDate: z.coerce.date().optional(),
  warningStatus: z.enum(["PERMANENT", "TEMPORARY"]).optional(),
  remark: z.string().optional(),
});
export type CreateEMployeeWarningDto = z.infer<typeof CreateEMployeeWarningSchema>;

export const UpdateEMployeeWarningSchema = z.object({
  employeeId: z.string().uuid().optional(),
  warningStartDate: z.coerce.date().optional(),
  warningEndDate: z.coerce.date().optional(),
  warningStatus: z.enum(["PERMANENT", "TEMPORARY"]).optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeWarningDto = z.infer<typeof UpdateEMployeeWarningSchema>;