// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeLeaveAdvisorResponseDto {
  id: string | null;
  employeeId: string;
  order: number;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeLeaveAdvisorSchema = z.object({
  employeeId: z.string().min(1, "EMployeeId is required"),
  order: z.number().int(),
  remark: z.string().optional(),
});
export type CreateEMployeeLeaveAdvisorDto = z.infer<typeof CreateEMployeeLeaveAdvisorSchema>;

export const UpdateEMployeeLeaveAdvisorSchema = z.object({
  employeeId: z.string().min(1).optional(),
  order: z.number().int().optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeLeaveAdvisorDto = z.infer<typeof UpdateEMployeeLeaveAdvisorSchema>;