// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeContractAdvisorResponseDto {
  id: string | null;
  employeeId: string;
  order: number;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeContractAdvisorSchema = z.object({
  employeeId: z.string().uuid("EMployeeId is required must be a valid UUID"),
  order: z.number().int(),
  remark: z.string().optional(),
});
export type CreateEMployeeContractAdvisorDto = z.infer<typeof CreateEMployeeContractAdvisorSchema>;

export const UpdateEMployeeContractAdvisorSchema = z.object({
  employeeId: z.string().uuid().optional(),
  order: z.number().int().optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeContractAdvisorDto = z.infer<typeof UpdateEMployeeContractAdvisorSchema>;