// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeProjectResponseDto {
  employeeId: string;
  projectId: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeProjectSchema = z.object({
  employeeId: z.string().uuid("EMployeeId is required must be a valid UUID"),
  projectId: z.string().uuid("PRojectId is required must be a valid UUID"),
  remark: z.string().optional(),
});
export type CreateEMployeeProjectDto = z.infer<typeof CreateEMployeeProjectSchema>;

export const UpdateEMployeeProjectSchema = z.object({
  employeeId: z.string().uuid().optional(),
  projectId: z.string().uuid().optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeProjectDto = z.infer<typeof UpdateEMployeeProjectSchema>;