// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EmployeeWarningResponseDto {
  id: string | null;
  employeeId: string;
  warningStartDate: Date;
  warningEndDate: Date | null;
  warningStatus: "PERMANENT" | "TEMPORARY" | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateEmployeeWarningSchema = z.object({
  employeeId: z.string().min(1, "EmployeeId is required"),
  warningStartDate: z.coerce.date(),
  warningEndDate: z.coerce.date().optional(),
  warningStatus: z.enum(["PERMANENT", "TEMPORARY"]).optional(),
  remark: z.string().optional(),
});
export type CreateEmployeeWarningDto = z.infer<typeof CreateEmployeeWarningSchema>;

export const UpdateEmployeeWarningSchema = z.object({
  employeeId: z.string().min(1).optional(),
  warningStartDate: z.coerce.date().optional(),
  warningEndDate: z.coerce.date().optional(),
  warningStatus: z.enum(["PERMANENT", "TEMPORARY"]).optional(),
  remark: z.string().optional(),
});
export type UpdateEmployeeWarningDto = z.infer<typeof UpdateEmployeeWarningSchema>;