// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface EMployeeWorkZoneResponseDto {
  id: string | null;
  employeeId: string;
  workingZoneId: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateEMployeeWorkZoneSchema = z.object({
  employeeId: z.string().uuid("EMployeeId is required must be a valid UUID"),
  workingZoneId: z.string().uuid("WOrkingZoneId is required must be a valid UUID"),
  remark: z.string().optional(),
});
export type CreateEMployeeWorkZoneDto = z.infer<typeof CreateEMployeeWorkZoneSchema>;

export const UpdateEMployeeWorkZoneSchema = z.object({
  employeeId: z.string().uuid().optional(),
  workingZoneId: z.string().uuid().optional(),
  remark: z.string().optional(),
});
export type UpdateEMployeeWorkZoneDto = z.infer<typeof UpdateEMployeeWorkZoneSchema>;