// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface GradeResponseDto {
  id: string;
  name: string;
  remark: string | null;
  stsActive: boolean | null;
  createdAt: Date;
  createdBy: string | null;
  updatedAt: Date | null;
  updatedBy: string | null;
  deletedAt: Date | null;
}

import { z } from "zod";

export const CreateGradeSchema = z.object({
  name: z.string().min(1, "Name is required"),
  remark: z.string().optional(),
});
export type CreateGradeDto = z.infer<typeof CreateGradeSchema>;

export const UpdateGradeSchema = z.object({
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateGradeDto = z.infer<typeof UpdateGradeSchema>;
