// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface PositionResponseDto {
  id: string | null;
  departmentId: string | null;
  name: string | null;
  isHod: boolean | null;
}

import { z } from "zod";

export const CreatePositionSchema = z.object({
  departmentId: z.string().optional(),
  name: z.string().optional(),
  isHod: z.boolean().optional(),
});
export type CreatePositionDto = z.infer<typeof CreatePositionSchema>;

export const UpdatePositionSchema = z.object({
  departmentId: z.string().optional(),
  name: z.string().optional(),
  isHod: z.boolean().optional(),
});
export type UpdatePositionDto = z.infer<typeof UpdatePositionSchema>;