// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface POsitionResponseDto {
  id: string | null;
  departmentId: string | null;
  name: string | null;
  isHod: boolean | null;
}

import { z } from "zod";

export const CreatePOsitionSchema = z.object({
  departmentId: z.string().optional(),
  name: z.string().optional(),
  isHod: z.boolean().optional(),
});
export type CreatePOsitionDto = z.infer<typeof CreatePOsitionSchema>;

export const UpdatePOsitionSchema = z.object({
  departmentId: z.string().optional(),
  name: z.string().optional(),
  isHod: z.boolean().optional(),
});
export type UpdatePOsitionDto = z.infer<typeof UpdatePOsitionSchema>;