// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface ProjectResponseDto {
  id: string | null;
  sapCode: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateProjectSchema = z.object({
  sapCode: z.string().min(1, "SapCode is required"),
  name: z.string().min(1, "Name is required"),
  remark: z.string().optional(),
});
export type CreateProjectDto = z.infer<typeof CreateProjectSchema>;

export const UpdateProjectSchema = z.object({
  sapCode: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateProjectDto = z.infer<typeof UpdateProjectSchema>;