// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface ReligionResponseDto {
  id: string | null;
  name: string;
  description: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateReligionSchema = z.object({
  name: z.string().min(1, "Name is required"),
  description: z.string().min(1, "Description is required"),
  remark: z.string().optional(),
});
export type CreateReligionDto = z.infer<typeof CreateReligionSchema>;

export const UpdateReligionSchema = z.object({
  name: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateReligionDto = z.infer<typeof UpdateReligionSchema>;