// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface TrainingResponseDto {
  id: string | null;
  companyId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateTrainingSchema = z.object({
  companyId: z.string().min(1, "CompanyId is required"),
  name: z.string().min(1, "Name is required"),
  remark: z.string().optional(),
});
export type CreateTrainingDto = z.infer<typeof CreateTrainingSchema>;

export const UpdateTrainingSchema = z.object({
  companyId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateTrainingDto = z.infer<typeof UpdateTrainingSchema>;