// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface TrainingTypeResponseDto {
  id: string | null;
  companyId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateTrainingTypeSchema = z.object({
  companyId: z.string().min(1, "CompanyId is required"),
  name: z.string().min(1, "Name is required"),
  remark: z.string().optional(),
});
export type CreateTrainingTypeDto = z.infer<typeof CreateTrainingTypeSchema>;

export const UpdateTrainingTypeSchema = z.object({
  companyId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateTrainingTypeDto = z.infer<typeof UpdateTrainingTypeSchema>;