// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface TrainingScheduleResponseDto {
  id: string | null;
  companyId: string;
  trainingDate: Date | null;
  trainingTime: string | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateTrainingScheduleSchema = z.object({
  companyId: z.string().min(1, "CompanyId is required"),
  trainingDate: z.coerce.date().optional(),
  trainingTime: z.string().optional(),
  remark: z.string().optional(),
});
export type CreateTrainingScheduleDto = z.infer<typeof CreateTrainingScheduleSchema>;

export const UpdateTrainingScheduleSchema = z.object({
  companyId: z.string().min(1).optional(),
  trainingDate: z.coerce.date().optional(),
  trainingTime: z.string().optional(),
  remark: z.string().optional(),
});
export type UpdateTrainingScheduleDto = z.infer<typeof UpdateTrainingScheduleSchema>;