// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface TRainingResponseDto {
  id: string | null;
  companyId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateTRainingSchema = z.object({
  companyId: z.string().uuid("COmpanyId is required must be a valid UUID"),
  name: z.string().min(1, "NAme is required"),
  remark: z.string().optional(),
});
export type CreateTRainingDto = z.infer<typeof CreateTRainingSchema>;

export const UpdateTRainingSchema = z.object({
  companyId: z.string().uuid().optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateTRainingDto = z.infer<typeof UpdateTRainingSchema>;