// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface TRainingTypeResponseDto {
  id: string | null;
  companyId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateTRainingTypeSchema = z.object({
  companyId: z.string().uuid("COmpanyId is required must be a valid UUID"),
  name: z.string().min(1, "NAme is required"),
  remark: z.string().optional(),
});
export type CreateTRainingTypeDto = z.infer<typeof CreateTRainingTypeSchema>;

export const UpdateTRainingTypeSchema = z.object({
  companyId: z.string().uuid().optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateTRainingTypeDto = z.infer<typeof UpdateTRainingTypeSchema>;