// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface TRainingScheduleResponseDto {
  id: string | null;
  companyId: string;
  trainingDate: Date | null;
  trainingTime: string | null;
  remark: string | null;
}

import { z } from "zod";

export const CreateTRainingScheduleSchema = z.object({
  companyId: z.string().uuid("COmpanyId is required must be a valid UUID"),
  trainingDate: z.coerce.date().optional(),
  trainingTime: z.string().optional(),
  remark: z.string().optional(),
});
export type CreateTRainingScheduleDto = z.infer<typeof CreateTRainingScheduleSchema>;

export const UpdateTRainingScheduleSchema = z.object({
  companyId: z.string().uuid().optional(),
  trainingDate: z.coerce.date().optional(),
  trainingTime: z.string().optional(),
  remark: z.string().optional(),
});
export type UpdateTRainingScheduleDto = z.infer<typeof UpdateTRainingScheduleSchema>;