// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface WarningResponseDto {
  id: string | null;
  companyId: string;
  warningGradeId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateWarningSchema = z.object({
  companyId: z.string().min(1, "CompanyId is required"),
  warningGradeId: z.string().min(1, "WarningGradeId is required"),
  name: z.string().min(1, "Name is required"),
  remark: z.string().optional(),
});
export type CreateWarningDto = z.infer<typeof CreateWarningSchema>;

export const UpdateWarningSchema = z.object({
  companyId: z.string().min(1).optional(),
  warningGradeId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateWarningDto = z.infer<typeof UpdateWarningSchema>;