// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface WArningResponseDto {
  id: string | null;
  companyId: string;
  warningGradeId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateWArningSchema = z.object({
  companyId: z.string().min(1, "COmpanyId is required"),
  warningGradeId: z.string().min(1, "WArningGradeId is required"),
  name: z.string().min(1, "NAme is required"),
  remark: z.string().optional(),
});
export type CreateWArningDto = z.infer<typeof CreateWArningSchema>;

export const UpdateWArningSchema = z.object({
  companyId: z.string().min(1).optional(),
  warningGradeId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateWArningDto = z.infer<typeof UpdateWArningSchema>;