// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface WArningGradeResponseDto {
  id: string | null;
  companyId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateWArningGradeSchema = z.object({
  companyId: z.string().min(1, "COmpanyId is required"),
  name: z.string().min(1, "NAme is required"),
  remark: z.string().optional(),
});
export type CreateWArningGradeDto = z.infer<typeof CreateWArningGradeSchema>;

export const UpdateWArningGradeSchema = z.object({
  companyId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateWArningGradeDto = z.infer<typeof UpdateWArningGradeSchema>;