// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface WarningGradeResponseDto {
  id: string | null;
  companyId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateWarningGradeSchema = z.object({
  companyId: z.string().min(1, "CompanyId is required"),
  name: z.string().min(1, "Name is required"),
  remark: z.string().optional(),
});
export type CreateWarningGradeDto = z.infer<typeof CreateWarningGradeSchema>;

export const UpdateWarningGradeSchema = z.object({
  companyId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateWarningGradeDto = z.infer<typeof UpdateWarningGradeSchema>;