// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface WorkingZoneResponseDto {
  id: string | null;
  companyId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateWorkingZoneSchema = z.object({
  companyId: z.string().min(1, "CompanyId is required"),
  name: z.string().min(1, "Name is required"),
  remark: z.string().optional(),
});
export type CreateWorkingZoneDto = z.infer<typeof CreateWorkingZoneSchema>;

export const UpdateWorkingZoneSchema = z.object({
  companyId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateWorkingZoneDto = z.infer<typeof UpdateWorkingZoneSchema>;