// Auto-generated by scripts/generate-dtos.ts — do not edit manually

export interface WOrkingZoneResponseDto {
  id: string | null;
  companyId: string;
  name: string;
  remark: string | null;
}

import { z } from "zod";

export const CreateWOrkingZoneSchema = z.object({
  companyId: z.string().min(1, "COmpanyId is required"),
  name: z.string().min(1, "NAme is required"),
  remark: z.string().optional(),
});
export type CreateWOrkingZoneDto = z.infer<typeof CreateWOrkingZoneSchema>;

export const UpdateWOrkingZoneSchema = z.object({
  companyId: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  remark: z.string().optional(),
});
export type UpdateWOrkingZoneDto = z.infer<typeof UpdateWOrkingZoneSchema>;