import "reflect-metadata";
import { Container } from "inversify";
import { drizzle, NodePgDatabase } from "drizzle-orm/node-postgres";
import { TYPES } from "./types";
import { CompanyRepository } from "@repositories/company/company.repository";
import { CompanyService } from "@services/company/company.service";
import { CountryRepository } from "@repositories/country/country.repository";
import { CountryService } from "@services/country/country.service";
import { ReligionRepository } from "@repositories/religion/religion.repository";
import { ReligionService } from "@services/religion/religion.service";
import { GradeRepository } from "@repositories/grade/grade.repository";
import { GradeService } from "@services/grade/grade.service";
import { CostCenterRepository } from "@repositories/costCenter/costCenter.repository";
import { CostCenterService } from "@services/costCenter/costCenter.service";
import { ProjectRepository } from "@repositories/project/project.repository";
import { ProjectService } from "@services/project/project.service";
import { DepartmentRepository } from "@repositories/departments/departments.repository";
import { DepartmentService } from "@services/departments/departments.service";
import { PositionRepository } from "@repositories/positions/positions.repository";
import { PositionService } from "@services/positions/positions.service";
import { AllowanceRepository } from "@repositories/allowances/allowances.repository";
import { AllowanceService } from "@services/allowances/allowances.service";
import { WarningGradeRepository } from "@repositories/warningGrades/warningGrades.repository";
import { WarningGradeService } from "@services/warningGrades/warningGrades.service";
import { WarningRepository } from "@repositories/warnings/warnings.repository";
import { WarningService } from "@services/warnings/warnings.service";
import { TrainingTypeRepository } from "@repositories/trainingTypes/trainingTypes.repository";
import { TrainingTypeService } from "@services/trainingTypes/trainingTypes.service";
import { TrainingRepository } from "@repositories/trainings/trainings.repository";
import { TrainingService } from "@services/trainings/trainings.service";
import { TrainingScheduleRepository } from "@repositories/trainingSchedules/trainingSchedules.repository";
import { TrainingScheduleService } from "@services/trainingSchedules/trainingSchedules.service";
import { WorkingZoneRepository } from "@repositories/workingZones/workingZones.repository";
import { WorkingZoneService } from "@services/workingZones/workingZones.service";
import { EmployeeRepository } from "@repositories/employees/employees.repository";
import { EmployeeService } from "@services/employees/employees.service";
import { EmployeeAddressRepository } from "@repositories/employeeAddresses/employeeAddresses.repository";
import { EmployeeAddressService } from "@services/employeeAddresses/employeeAddresses.service";
import { EmployeeContractRepository } from "@repositories/employeeContracts/employeeContracts.repository";
import { EmployeeContractService } from "@services/employeeContracts/employeeContracts.service";
import { EmployeeContractAdvisorRepository } from "@repositories/employeeContractAdvisors/employeeContractAdvisors.repository";
import { EmployeeContractAdvisorService } from "@services/employeeContractAdvisors/employeeContractAdvisors.service";
import { EmployeeLeaveAdvisorRepository } from "@repositories/employeeLeaveAdvisors/employeeLeaveAdvisors.repository";
import { EmployeeLeaveAdvisorService } from "@services/employeeLeaveAdvisors/employeeLeaveAdvisors.service";
import { EmployeeMcuRepository } from "@repositories/employeeMcus/employeeMcus.repository";
import { EmployeeMcuService } from "@services/employeeMcus/employeeMcus.service";
import { EmployeeProjectRepository } from "@repositories/employeeProjects/employeeProjects.repository";
import { EmployeeProjectService } from "@services/employeeProjects/employeeProjects.service";
import { EmployeeTrainingRepository } from "@repositories/employeeTrainings/employeeTrainings.repository";
import { EmployeeTrainingService } from "@services/employeeTrainings/employeeTrainings.service";
import { EmployeeWarningRepository } from "@repositories/employeeWarnings/employeeWarnings.repository";
import { EmployeeWarningService } from "@services/employeeWarnings/employeeWarnings.service";
import { EmployeeWorkZoneRepository } from "@repositories/employeeWorkZones/employeeWorkZones.repository";
import { EmployeeWorkZoneService } from "@services/employeeWorkZones/employeeWorkZones.service";

const container = new Container();

// Database — concrete instance, no interface
container.bind<NodePgDatabase>(TYPES.Database).toConstantValue(
  drizzle({ connection: process.env.DATABASE_URL!, casing: "snake_case" }),
);
// Repository
container.bind(TYPES.CompanyRepositoryInterface).to(CompanyRepository);
container.bind(TYPES.CountryRepositoryInterface).to(CountryRepository);
container.bind(TYPES.ReligionRepositoryInterface).to(ReligionRepository);
container.bind(TYPES.GradeRepositoryInterface).to(GradeRepository);
container.bind(TYPES.CostCenterRepositoryInterface).to(CostCenterRepository);
container.bind(TYPES.ProjectRepositoryInterface).to(ProjectRepository);
container.bind(TYPES.DepartmentRepositoryInterface).to(DepartmentRepository);
container.bind(TYPES.PositionRepositoryInterface).to(PositionRepository);
container.bind(TYPES.AllowanceRepositoryInterface).to(AllowanceRepository);
container.bind(TYPES.WarningGradeRepositoryInterface).to(WarningGradeRepository);
container.bind(TYPES.WarningRepositoryInterface).to(WarningRepository);
container.bind(TYPES.TrainingTypeRepositoryInterface).to(TrainingTypeRepository);
container.bind(TYPES.TrainingRepositoryInterface).to(TrainingRepository);
container.bind(TYPES.TrainingScheduleRepositoryInterface).to(TrainingScheduleRepository);
container.bind(TYPES.WorkingZoneRepositoryInterface).to(WorkingZoneRepository);
container.bind(TYPES.EmployeeRepositoryInterface).to(EmployeeRepository);
container.bind(TYPES.EmployeeAddressRepositoryInterface).to(EmployeeAddressRepository);
container.bind(TYPES.EmployeeContractRepositoryInterface).to(EmployeeContractRepository);
container.bind(TYPES.EmployeeContractAdvisorRepositoryInterface).to(EmployeeContractAdvisorRepository);
container.bind(TYPES.EmployeeLeaveAdvisorRepositoryInterface).to(EmployeeLeaveAdvisorRepository);
container.bind(TYPES.EmployeeMcuRepositoryInterface).to(EmployeeMcuRepository);
container.bind(TYPES.EmployeeProjectRepositoryInterface).to(EmployeeProjectRepository);
container.bind(TYPES.EmployeeTrainingRepositoryInterface).to(EmployeeTrainingRepository);
container.bind(TYPES.EmployeeWarningRepositoryInterface).to(EmployeeWarningRepository);
container.bind(TYPES.EmployeeWorkZoneRepositoryInterface).to(EmployeeWorkZoneRepository);

// Service
container.bind(TYPES.CompanyServiceInterface).to(CompanyService);
container.bind(TYPES.CountryServiceInterface).to(CountryService);
container.bind(TYPES.ReligionServiceInterface).to(ReligionService);
container.bind(TYPES.GradeServiceInterface).to(GradeService);
container.bind(TYPES.CostCenterServiceInterface).to(CostCenterService);
container.bind(TYPES.ProjectServiceInterface).to(ProjectService);
container.bind(TYPES.DepartmentServiceInterface).to(DepartmentService);
container.bind(TYPES.PositionServiceInterface).to(PositionService);
container.bind(TYPES.AllowanceServiceInterface).to(AllowanceService);
container.bind(TYPES.WarningGradeServiceInterface).to(WarningGradeService);
container.bind(TYPES.WarningServiceInterface).to(WarningService);
container.bind(TYPES.TrainingTypeServiceInterface).to(TrainingTypeService);
container.bind(TYPES.TrainingServiceInterface).to(TrainingService);
container.bind(TYPES.TrainingScheduleServiceInterface).to(TrainingScheduleService);
container.bind(TYPES.WorkingZoneServiceInterface).to(WorkingZoneService);
container.bind(TYPES.EmployeeServiceInterface).to(EmployeeService);
container.bind(TYPES.EmployeeAddressServiceInterface).to(EmployeeAddressService);
container.bind(TYPES.EmployeeContractServiceInterface).to(EmployeeContractService);
container.bind(TYPES.EmployeeContractAdvisorServiceInterface).to(EmployeeContractAdvisorService);
container.bind(TYPES.EmployeeLeaveAdvisorServiceInterface).to(EmployeeLeaveAdvisorService);
container.bind(TYPES.EmployeeMcuServiceInterface).to(EmployeeMcuService);
container.bind(TYPES.EmployeeProjectServiceInterface).to(EmployeeProjectService);
container.bind(TYPES.EmployeeTrainingServiceInterface).to(EmployeeTrainingService);
container.bind(TYPES.EmployeeWarningServiceInterface).to(EmployeeWarningService);
container.bind(TYPES.EmployeeWorkZoneServiceInterface).to(EmployeeWorkZoneService);

export { container };
